### ISSUE TITLE
How to unmask field in smartlook-client

### ISSUE THREAD

**Issue by kislasi** [smartlook/smartlook-rest-api-issue-tracker#1]
Hi,

We're using the npm package [smartlook-client](https://www.npmjs.com/package/smartlook-client) in our angular web application.
in our project settings 'record form inputs' is disabled (all the inputs are auto masked).
so we're wondering if it's possible to unmask a specific input.

**Comment by janzal** [comment]
Hi @kislasi,

this is an issue tracker for the [Smartlook REST API](https://docs.smartlook.com/docs/rest-api/overview). For any issues related to our Web SDK check its Github [here](https://github.com/smartlook/smartlook-client/issues).

However your issue might be covered in the official docs - https://docs.smartlook.com/docs/web/sensitive-data-protection
